version: "3.3"
services:
  sparql:
    image: stain/jena-fuseki:4.8.0
    environment:
      - ADMIN_PASSWORD=
      - FUSEKI_DATASET_1=dataset
      - JVM_ARGS=-Xmx1g
      - TDB=2
    ports:
      - "3030:3030"
    volumes:
      - ./data/fuseki:/fuseki
